ingress:
  enabled: true
  domains: []
  sniCatchallEnabled: false

zebra:
  enabled: false
  name: zebra
  testnet: false
  image:
    repository: zfnd/zebra
    tag: v2.0.1
    hash: 2daab3567d02c5b836918f69acaa8f6af2a0eab20e74396709c55eb1647bd4f1
    pullPolicy: IfNotPresent
  replicas: 1
  initSnapshot:
    enabled: false
    url: https://link.storjshare.io/s/jv62jmwhs3n6c7usknlv4ux4lbza/nodedumps/zec/zebra-2024-03-25.tar?download=1
  additionalEnv: {}
  volumes:
    data:
      size: 400Gi
  service:
    type: ClusterIP
  requests: {}
  # requests:
  #   cpu: 2
  #   memory: 4Gi
  # limits:
  #   memory: 16Gi

zcashd:
  enabled: false
  name: zcashd
  testnet: false
  image:
    repository: electriccoinco/zcashd
    tag: v6.0.0
    hash: cd3d6d3576c31efd6e4c1b017beac5585d236aefb27b6cb90a9f1142e94337eb
    pullPolicy: IfNotPresent
  replicas: 1
  initSnapshot:
    enabled: false
    url: https://link.storjshare.io/s/jx5wylg5q6hyg2myyah5eldbjs7q/nodedumps/zec/zcashd-2024-03-31.tar?download=1
    explorer_url: https://link.storjshare.io/s/jvyxajyevhmuyzsjlobsmv5enguq/nodedumps/zec/zcashd-explorer-2024-11-20.tar?download=1
  reindex: false
  lightwalletd: true
  explorer: false
  nodes:
   - mainnet.z.cash
  additionalArgs: []
  volumes:
    data:
      size: 400Gi
  service:
    type: ClusterIP
  requests: {}
  # requests:
  #   cpu: 1
  #   memory: 1.5Gi
  limits:
    memory: 6Gi

rpc:
  credentials:
    rpcUser: 100ZECS
    rpcPassword: h3hqw3eRHcoqwirhOCQWHEr2OC

lightwalletd:
  enabled: true
  name: lightwalletd
  rpcService: zebra
  image:
    repository: electriccoinco/lightwalletd
    tag: v0.4.17
    hash: 906942c30d84a017e76ce72c4d59787aa5208b87a4af1b724e700f8524ab4fd1
    pullPolicy: IfNotPresent
  replicas: 1
  initSnapshot:
    enabled: false
    url: https://link.storjshare.io/s/jvfegr7l7gwgcsvdml5lazlnypdq/nodedumps/zec/lwd/2024-03-26.tar?download=1
  additionalArgs: []
  volumes:
    data:
      size: 40Gi
  service:
    type: ClusterIP
  requests: {}
  # requests:
  #   cpu: 0.5
  #   memory: 512Mi
  limits:
    memory: 3Gi

explorer:
  enabled: false
  name: explorer
  replicas: 1
  image:
    repository: emersonian/zcash-explorer
    tag: v0.0.5
    hash: a509e56edbf4469e73355aac7bcaf99ccd2f42cbc1cfeb23bd7d8cbc1190406c
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4000
  resources:
    limits:
      cpu: "1"
      memory: "3072Mi"
    requests:
      cpu: "0.1"
      memory: "512Mi"
  env:
    # NOTE: Override this if you want cookies to store sensitive information.
    # Generate it with Elixir and Phoenix installed: "mix phx.gen.secret"
    SECRET_KEY_BASE: 552Ean5DQvRgWpbO/xR4HADdPkNz30mKICmkzuqWUvp+2e1NZderMWVA/v6KkcfJ
    EXPLORER_SCHEME: https
    EXPLORER_PORT: "4000"
    ZCASH_NETWORK: mainnet
    zcash_network: mainnet

global:
  # TODO: minimum volume size (Vultr is 40Gi for HDD, 10Gi for SSD), backport this to Thorchain and Maya
  images:
    busybox:
      tag: latest
      hash: 4be429a5fbb2e71ae7958bfa558bc637cf3a61baf40a708cb8fff532b39e52d0
    alpine:
      tag: latest
      hash: c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
