version: '3.8'

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    environment:
      - CADDY_EMAIL=${CADDY_EMAIL:-example@domain.com}
    depends_on:
      - lightwalletd 