{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.sniCatchallEnabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: tcp-ingress-route-all
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ .Values.lightwalletd.name }}
      port: 9067
{{- end }}
{{- end }}