{{- if .Values.ingress.enabled }}
{{ $lightwalletdService := .Values.lightwalletd.name }}
{{- range $index, $domain := .Values.ingress.domains }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: tcp-ingress-route-{{ $domain }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`{{ $domain }}`)
    services:
    - name: {{ $lightwalletdService }}
      port: 9067
  tls:
    certResolver: letsencrypt
    domains:
    - main: {{ $domain }}
---
{{- end }}
{{- end }}