{{- if .Values.zcashd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.zcashd.name }}-config
data:
  zcashd.conf: |
    txindex=1
    lightwalletd=1
    experimentalfeatures=1
    rpcuser={{ .Values.rpc.credentials.rpcUser }}
    rpcpassword={{ .Values.rpc.credentials.rpcPassword }}
    rpcbind=0.0.0.0
    rpcallowip=0.0.0.0/0
    {{- if .Values.zcashd.testnet }}
    testnet=1
    {{- end }}
{{- end }}