{{- if .Values.zebra.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.zebra.name }}-config
data:
  zebrad.toml: |
    [network]
    {{- if .Values.zebra.testnet }}
    network = "Testnet"
    {{- else }}
    network = "Mainnet"
    {{- end }}
    listen_addr = "0.0.0.0"
    [state]
    cache_dir = "/var/cache/zebrad-cache"
    [rpc]
    listen_addr = "0.0.0.0:8232"
    enable_cookie_auth = false
    parallel_cpu_threads = 0
    [tracing]
    use_color = false
{{- end }}
