{{- if .Values.zebra.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.zebra.name }}
spec:
  serviceName: {{ .Values.zebra.name }}-service
  replicas: {{ .Values.zebra.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.zebra.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.zebra.name }}
    spec:
      initContainers:
      {{- if .Values.zebra.initSnapshot.enabled }}
      - name: restore-snapshot
        image: alpine:{{ .Values.global.images.alpine.tag }}@sha256:{{ .Values.global.images.alpine.hash }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            if [ -z "$(ls -A /data | grep -v '^lost+found$')" ]; then
              echo "Volume is empty. Downloading and extracting snapshot...";
              wget -qO- "{{ .Values.zebra.initSnapshot.url }}" | tar --strip-components=1 -xvf - -C /data
              echo "Download and extraction complete.";
            else
              echo "Volume is not empty. Skipping download and extraction.";
            fi
            chown -R 2001 /data
        volumeMounts:
        - name: {{ .Values.zebra.name }}-data
          mountPath: /data
      {{- else }}
      - name: set-permissions
        image: busybox:{{ .Values.global.images.busybox.tag }}@sha256:{{ .Values.global.images.busybox.hash }}
        command: ["/bin/sh", "-c"]
        args:
          - chown -R 2001 /data
        volumeMounts:
        - name: {{ .Values.zebra.name }}-data
          mountPath: /data
      {{- end }}
      containers:
      - name: zebra
        image: {{ .Values.zebra.image.repository }}:{{ .Values.zebra.image.tag }}@sha256:{{ .Values.zebra.image.hash }}
        imagePullPolicy: {{ .Values.zebra.image.pullPolicy }}
        command: ["zebrad", "-c", "/etc/zebrad/zebrad.toml"]
        ports:
        - containerPort: 8232
          name: zebra-rpc
        - containerPort: 8233
          name: zebra-p2p
        volumeMounts:
        - name: {{ .Values.zebra.name }}-data
          mountPath: /var/cache/zebrad-cache
        - name: zebra-config
          mountPath: /etc/zebrad/
        resources:
          requests:
            cpu: {{ .Values.zebra.requests.cpu }}
            memory: {{ .Values.zebra.requests.memory }}
          {{- if .Values.zebra.limits }}
          limits:
            {{- if .Values.zebra.limits.memory }}
            memory: {{ .Values.zebra.limits.memory }}
            {{- end }}
          {{- end }}
      volumes:
      - name: zebra-config
        configMap:
          name: {{ .Values.zebra.name }}-config
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.zebra.name }}-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.zebra.volumes.data.size }}
      {{- if .Values.zebra.storageClassName }}
      storageClassName: {{ .Values.zebra.storageClassName }}
      {{- end }}
{{- end }}
