{{- if .Values.lightwalletd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.lightwalletd.name }}-config
data:
  zcash.conf: |
    rpcbind={{ .Values.lightwalletd.rpcService }}
    rpcport={{ if .Values.zcashd.testnet }}18232{{ else }}8232{{ end }}
    rpcuser={{ .Values.rpc.credentials.rpcUser }}
    rpcpassword={{ .Values.rpc.credentials.rpcPassword }}
{{- end }}