{{- if .Values.zaino.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.zaino.name }}-config
data:
  zaino.toml: |
    network = "{{ if .Values.zebra.testnet }}Testnet{{ else }}Mainnet{{ end }}"
    grpc_listen_address = "0.0.0.0:8137"
    grpc_tls = false
    tls_cert_path = "None"
    tls_key_path = "None"
    validator_listen_address = "{{ .Values.zaino.rpcService }}:{{ if .Values.zebra.testnet }}18232{{ else }}8232{{ end }}"
    validator_cookie_auth = false
    validator_cookie_path = "None"
    validator_user = "None"
    validator_password = "None"
    map_capacity = "None"
    map_shard_amount = "None"
    db_path = "/home/zaino/.cache/zaino"
    db_size = "{{ .Values.zaino.config.dbSize }}"
    no_sync = {{ .Values.zaino.config.noSync }}
    no_db = {{ .Values.zaino.config.noDB }}
    no_state = {{ .Values.zaino.config.noState }}
{{- end }}