{{- if .Values.zcashd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zcashd.name }}
spec:
  type: {{ .Values.zcashd.service.type }}
  selector:
    app: {{ .Values.zcashd.name }}
  ports:
    - port: {{ if .Values.zcashd.testnet }}18232{{ else }}8232{{ end }}
      targetPort: {{ if .Values.zcashd.testnet }}18232{{ else }}8232{{ end }}
      protocol: TCP
      name: rpc
{{- end }}