{{- if .Values.zebra.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zebra.name }}
spec:
  type: {{ .Values.zebra.service.type }}
  selector:
    app: {{ .Values.zebra.name }}
  ports:
    - port: {{ if .Values.zebra.testnet }}18232{{ else }}8232{{ end }}
      targetPort: {{ if .Values.zebra.testnet }}18232{{ else }}8232{{ end }}
      protocol: TCP
      name: rpc
{{- end }}