ingress:
  enabled: true
  domains: []
  sniCatchallEnabled: false

zebra:
  enabled: false
  name: zebra
  testnet: false
  image:
    repository: zfnd/zebra
    tag: v2.2.0
    hash: 7f1553efdf7314385c4ad82a1c24049ac4a3a64e926844d37b46f8c63199f9f0
    pullPolicy: IfNotPresent
  replicas: 1
  initSnapshot:
    enabled: false
    url: https://link.storjshare.io/s/jv62jmwhs3n6c7usknlv4ux4lbza/nodedumps/zec/zebra-2024-03-25.tar?download=1
  additionalEnv: {}
  volumes:
    data:
      size: 400Gi
  service:
    type: ClusterIP
  requests: {}
  # requests:
  #   cpu: 2
  #   memory: 4Gi
  # limits:
  #   memory: 16Gi

zcashd:
  enabled: false
  name: zcashd
  testnet: false
  image:
    repository: electriccoinco/zcashd
    tag: v6.1.0
    hash: 3c4e814d637333355c206f1b4260db21d225c8f5993040ef099a8c7172a84f70
    pullPolicy: IfNotPresent
  replicas: 1
  initSnapshot:
    enabled: false
    url: https://link.storjshare.io/s/jx5wylg5q6hyg2myyah5eldbjs7q/nodedumps/zec/zcashd-2024-03-31.tar?download=1
    explorer_url: https://link.storjshare.io/s/jvyxajyevhmuyzsjlobsmv5enguq/nodedumps/zec/zcashd-explorer-2024-11-20.tar?download=1
  reindex: false
  lightwalletd: true
  explorer: false
  nodes:
   - mainnet.z.cash
  additionalArgs: []
  volumes:
    data:
      size: 400Gi
  service:
    type: ClusterIP
  requests:
    cpu: 1
    memory: 1.5Gi
  limits:
    memory: 10Gi
  mine: false
  mining_address:
  genproclimit: 1

rpc:
  credentials:
    rpcUser: 100ZECS
    rpcPassword: h3hqw3eRHcoqwirhOCQWHEr2OC

lightwalletd:
  enabled: true
  name: lightwalletd
  rpcService: zebra
  donationAddress:
  image:
    repository: electriccoinco/lightwalletd
    tag: v0.4.17
    hash: 906942c30d84a017e76ce72c4d59787aa5208b87a4af1b724e700f8524ab4fd1
    pullPolicy: IfNotPresent
  replicas: 1
  initSnapshot:
    enabled: false
    url: https://link.storjshare.io/s/jvfegr7l7gwgcsvdml5lazlnypdq/nodedumps/zec/lwd/2024-03-26.tar?download=1
  additionalArgs: []
  volumes:
    data:
      size: 40Gi
  service:
    type: ClusterIP
  requests:
    cpu: 0.5
    memory: 512Mi
  limits:
    memory: 3Gi

explorer:
  enabled: false
  name: explorer
  replicas: 1
  image:
    repository: emersonian/zcash-explorer
    tag: v0.0.6
    hash: ff583282563a566c09d004cd4bdf2f30edd32497a3a98eec40df1da130a69df9
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 4000
  resources:
    limits:
      cpu: "1"
      memory: "3072Mi"
    requests:
      cpu: "0.1"
      memory: "512Mi"
  env:
    # NOTE: Override this if you want cookies to store sensitive information.
    # Generate it with Elixir and Phoenix installed: "mix phx.gen.secret"
    SECRET_KEY_BASE: 552Ean5DQvRgWpbO/xR4HADdPkNz30mKICmkzuqWUvp+2e1NZderMWVA/v6KkcfJ
    EXPLORER_SCHEME: https
    EXPLORER_PORT: "4000"
    ZCASH_NETWORK: mainnet
    zcash_network: mainnet

zaino:
  enabled: false
  name: zaino
  ingress:
    enabled: true
    domains: []
  image:
    repository: emersonian/zcash-zaino
    tag: 0.1.2-zr4
    hash: 9965cc15e018c2c8cc3d3ce708717f25191f00cb7175f3eb35cb1bfd993fc7d5
    pullPolicy: IfNotPresent
  replicas: 1
  rpcService: zebra
  volumes:
    data:
      size: 40Gi
  service:
    type: ClusterIP
    port: 8137
  requests:
    cpu: 0.5
    memory: 512Mi
  limits:
    memory: 6Gi
  additionalArgs: []
  config:
    dbSize: 64
    noSync: false
    noDB: false
    noState: false

global:
  # TODO: minimum volume size (Vultr is 40Gi for HDD, 10Gi for SSD), backport this to Thorchain and Maya
  images:
    busybox:
      tag: latest
      hash: 4be429a5fbb2e71ae7958bfa558bc637cf3a61baf40a708cb8fff532b39e52d0
    alpine:
      tag: latest
      hash: c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
